# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_card2',
                'doc_host': 'https://falconkinder810.github.io',
                'git_url': 'https://github.com/falconkinder810/nbdev_card2',
                'lib_path': 'nbdev_card2'},
  'syms': { 'nbdev_card2.card': { 'nbdev_card2.card.Card': ('card.html#card', 'nbdev_card2/card.py'),
                                  'nbdev_card2.card.Card.__init__': ('card.html#card.__init__', 'nbdev_card2/card.py'),
                                  'nbdev_card2.card.Card.__str__': ('card.html#card.__str__', 'nbdev_card2/card.py')}}}
