# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 5
suits = ["\u2663", "\u2666", "\u2665", "\u2660"]
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 10
class Card:
    "A playing card, created by passing in `rank` and `suit`"
    suits = ["\u2663", "\u2666", "\u2665", "\u2660"]
    ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]
    def __init__(self,
                 suit:int,  # shape of cards in integer
                 rank:int): # rank of cards in integer
        self.suit, self.rank = suit, rank
    def __str__(self): return f'{self.ranks[self.rank]} {self.suits[self.suit]}'
    __repr__ = __str__
